
package br.com.klayrocha;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerPort", targetNamespace = "http://klayrocha.com.br")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerPort {


    /**
     * 
     * @param getCustomerDetailRequest
     * @return
     *     returns br.com.klayrocha.GetCustomerDetailResponse
     */
    @WebMethod(operationName = "GetCustomerDetail")
    @WebResult(name = "GetCustomerDetailResponse", targetNamespace = "http://klayrocha.com.br", partName = "GetCustomerDetailResponse")
    public GetCustomerDetailResponse getCustomerDetail(
        @WebParam(name = "GetCustomerDetailRequest", targetNamespace = "http://klayrocha.com.br", partName = "GetCustomerDetailRequest")
        GetCustomerDetailRequest getCustomerDetailRequest);

    /**
     * 
     * @param getAllCustomerRequest
     * @return
     *     returns br.com.klayrocha.GetAllCustomerResponse
     */
    @WebMethod(operationName = "GetAllCustomer")
    @WebResult(name = "GetAllCustomerResponse", targetNamespace = "http://klayrocha.com.br", partName = "GetAllCustomerResponse")
    public GetAllCustomerResponse getAllCustomer(
        @WebParam(name = "GetAllCustomerRequest", targetNamespace = "http://klayrocha.com.br", partName = "GetAllCustomerRequest")
        GetAllCustomerRequest getAllCustomerRequest);

    /**
     * 
     * @param deleteCustomerRequest
     * @return
     *     returns br.com.klayrocha.DeleteCustomerResponse
     */
    @WebMethod(operationName = "DeleteCustomer")
    @WebResult(name = "DeleteCustomerResponse", targetNamespace = "http://klayrocha.com.br", partName = "DeleteCustomerResponse")
    public DeleteCustomerResponse deleteCustomer(
        @WebParam(name = "DeleteCustomerRequest", targetNamespace = "http://klayrocha.com.br", partName = "DeleteCustomerRequest")
        DeleteCustomerRequest deleteCustomerRequest);

}
